export const ACCOUNT_TYPE = [
  {
    label: 'ENUM.LEDGER',
    value: 0,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.BANK',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.VENDOR',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const DEFAULT_BIT = [
  {
    label: 'ENUM.DEFAULT_BIT_ALL',
    value: null,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.DEFAULT_BIT_TRUE',
    value: true,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.DEFAULT_BIT_FALSE',
    value: false,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const GENDAR = [
  {
    label: 'ENUM.MALE',
    value: 0,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.FEMALE',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
// export const EMPLOYEE_STATUS = [ // enum เก่า
//   {
//     label: 'ENUM.PROBATION',
//     value: 0,
//     styleClass: null,
//     icon: null,
//     title: null,
//     disabled: false,
//   },
//   {
//     label: 'ENUM.THROUGH_WORK',
//     value: 1,
//     styleClass: null,
//     icon: null,
//     title: null,
//     disabled: false,
//   },
//   {
//     label: 'ENUM.RESIGN',
//     value: 2,
//     styleClass: null,
//     icon: null,
//     title: null,
//     disabled: false,
//   },
//   {
//     label: 'ENUM.BACK_TO_WORK',
//     value: 3,
//     styleClass: null,
//     icon: null,
//     title: null,
//     disabled: false,
//   },
//   {
//     label: 'ENUM.EXTEND_PROBATION_PERIOD',
//     value: 4,
//     styleClass: null,
//     icon: null,
//     title: null,
//     disabled: false,
//   },
// ];
export const EMPLOYEE_STATUS = [
  {
    label: 'ENUM.PROBATION',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.NORMAL',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.RESIGN',
    value: 3,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const TITLE = [
  {
    label: 'ENUM.MR',
    value: 0,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.MISS',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.Mrs',
    value: 3,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const EDUCATION_LEVEL = [
  {
    label: 'ENUM.ELEMENTARY_SCHOOL',
    value: 0,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.NON_FORMAI_EDUCATION',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.JUNIONR_HIGH_SCOOL',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.SENIOR_HIGH_SCOOL',
    value: 3,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.VOCATIONAL_CERTIFICATE',
    value: 4,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.HIGH_VOCATIONAL_CERTIFICATE',
    value: 5,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.BACHELOR_DEGREE',
    value: 6,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.MASTERS_DEGREE',
    value: 7,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.DOCTORATE_DEGREE',
    value: 8,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const REFTYPE = [
  {
    label: 'ENUM.ASSESS_RIGHT',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ADDRESS',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ASSESSMENT_TRANS',
    value: 3,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ASSETS_CATEGORY',
    value: 4,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ASSETS',
    value: 5,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ATTACHMENT',
    value: 6,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.BACKTOWORK',
    value: 7,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.BANK_CATEGORY',
    value: 8,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.BANK',
    value: 9,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.BLACKLIST',
    value: 10,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.BOOK_BANK',
    value: 11,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.BRAN',
    value: 12,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.BUDGETING',
    value: 13,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.CERTIFICATE_TRANS',
    value: 14,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.COMPANY_CATEGORY',
    value: 15,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.COMPANY',
    value: 16,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.CONTACT_PERSON',
    value: 17,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.CONTACT',
    value: 18,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.COUNTRY',
    value: 19,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.CURRENCY',
    value: 20,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.CUSTOMER_BRANCH',
    value: 21,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.CUSTOMER_CATEGORY',
    value: 22,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.CUSTOMER',
    value: 23,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.CUSTOMER_TYPE',
    value: 24,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.DEPARTMENT',
    value: 25,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.DEPRECIATION',
    value: 26,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.DISTRICT',
    value: 27,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.DOCUMENT_STATUS',
    value: 28,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.EDUCATION',
    value: 29,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.EMERGENCY_CONTACT',
    value: 30,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.EMPLOYEE_CATEGORY',
    value: 31,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.EMPLOYEE_STATUS',
    value: 32,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.EMPLOYEE',
    value: 33,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.GENERAL_LEDGER',
    value: 34,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.INVENTORY_CATEGORY',
    value: 35,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ITEMS_CATEGORY',
    value: 36,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ITEMS_SECTION',
    value: 37,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ITEMS',
    value: 38,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.JOB_DESCRIPTION',
    value: 39,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.JOB_LEVEL',
    value: 40,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.LEAVE_TRANS',
    value: 41,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.LEAVE_TRANS_TYPE',
    value: 42,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.LOAN_RECEIVABLE',
    value: 43,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.MACHINE_CATEGORY',
    value: 44,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.MACHINE',
    value: 45,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.NATIONALITY',
    value: 46,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.OUTSITE',
    value: 47,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.PAYMENT_METHOD',
    value: 48,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.PATROLL',
    value: 49,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.POSITION',
    value: 50,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.PRODUCT_CATEGORY',
    value: 51,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.PRODUCT',
    value: 52,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.PROVINCE',
    value: 53,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.PURCHASE_HEADER',
    value: 54,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.PURCHASE_LINE',
    value: 55,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.PURCHASE_METHODE',
    value: 56,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.PURCHASE_ORDER',
    value: 57,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.RECEIVE_METHOD',
    value: 58,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.REGISTER_STATION',
    value: 59,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.RESPONSIVE_DEVICE',
    value: 60,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ROLE',
    value: 61,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.SARALY',
    value: 62,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.SPARE_PART_TB',
    value: 63,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.STATUS',
    value: 64,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.SUB_DISTRICT',
    value: 65,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.SUPLIER_BRANCH',
    value: 66,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.SUPLIER',
    value: 67,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.SUPLIER_CATEGORY',
    value: 68,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.TAX',
    value: 69,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.TIME_TICKET',
    value: 70,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.TRAINING_TRANS_DETAIL',
    value: 71,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.TRAINING_TRANS',
    value: 72,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.UNIT',
    value: 73,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.USER',
    value: 74,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.VEHICLE_CATEGORY',
    value: 75,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.VEHICLE',
    value: 76,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.WAREHOUSE',
    value: 77,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.WARNING_TRANS',
    value: 78,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.WELFARE_DETAIL',
    value: 79,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.WELFARE',
    value: 80,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.WORKTIMETYPE',
    value: 81,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.CERTIFICATE_TYPE',
    value: 82,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ASSESSMENT_TRANS_TYPE_TB',
    value: 83,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.PROBATION_TRANS',
    value: 86,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const MARNING_TRANS_TYPE = [
  {
    label: 'ENUM.SPEECH',
    value: 0,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.1_ST_WRITING',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.2_ST_WRITING',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.GIVE_OUT',
    value: 3,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const SYS_LANGUAGE = [
  {
    label: 'ENUM.SYS_LANGUAGE_EN',
    value: 'en',
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.SYS_LANGUAGE_TH',
    value: 'th',
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const EMPLOYEE_TYPE = [
  {
    label: 'ENUM.MONTH_EMP',
    value: 10,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.DAY_EMP',
    value: 20,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const WORKTIMETYPE = [
  {
    label: 'ENUM.NT',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.OT',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
  {
    label: 'ENUM.ET',
    value: 3,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];

export const TEMPLATE_TYPE = [
  {
    label: 'ENUM.EMP_DATA',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.CUS_DATA',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const MOVE_TYPE = [
  {
    label: 'ENUM.IN',
    value: 0,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.OUT',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.RETURN',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.CUT',
    value: 3,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const REVISION_TIME_TYPE = [
  {
    label: 'ENUM.CREATE_NEW_TIMETICKET',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.UPDATE_OLD_TIMETICKET',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
export const BANK_CATEGORY = [
  {
    label: 'ENUM.SAVING',
    value: 0,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.DAILY_STREAM',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.FIXED_DEPOSIT',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.FOREIGN_CURRENCY_DEPOSIT',
    value: 3,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];

export const MARITAL_STATUS = [
  {
    label: 'ENUM.SINGLE',
    value: 0,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.GET_MARRIED',
    value: 1,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },

  {
    label: 'ENUM.DIVORCE',
    value: 2,
    styleClass: null,
    icon: null,
    title: null,
    disabled: false,
  },
];
